spring:
  profiles:
    active: dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: dev
  application:
    name: dev-microservice-product-applicationName # 表格中 Application 中显示的名字

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka, http://localhost:6002/eureka
  instance:
    instance-id: laiyu-provider-product1111 # 表格上 status 显示的服务名字
logging:
  level:
    root: info

---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: prod
  application:
    name: prod-microservice-product-applicationName # 表格中 Application 中显示的名字

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka, http://localhost:6002/eureka
  instance:
    instance-id: laiyu-provider-product1111 # 表格上 status 显示的服务名字
logging:
  level:
    root: info