spring:
  profiles:
    active: dev
---
server:
  port: 6001
eureka:
  instance:
    hostname: eureka6001.com
    prefer-ip-address: true
  client:
    register-with-eureka: false # false 表示不把自己注册到 eureka 服务器中
    fetch-registry: false # 表示自己不从 eureka 服务器中获取别人的注册信息
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka # 如果是单机版，写自己的，如果是集群，写对方的
  server:
    enable-self-preservation: false
spring:
  profiles: dev
  application: 
    name: dev-eureka-server-applicationName

---
server:
  port: 6001
eureka:
  instance:
    hostname: eureka6001.com
    prefer-ip-address: true
  client:
    register-with-eureka: false # false 表示不把自己注册到 eureka 服务器中
    fetch-registry: false # 表示自己不从 eureka 服务器中获取别人的注册信息
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka # 如果是单机版，写自己的，如果是集群，写对方的
  server:
    enable-self-preservation: false
spring:
  profiles: prod
  application: 
    name: dev-eureka-server-applicationName
